services:
  portfolio:
    build: .
    container_name: mon-portfolio
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./src:/usr/share/nginx/html
      - ./assets:/usr/share/nginx/html/assets
